# Generated by Django 3.2.6 on 2021-08-29 15:26

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Profiles', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TRUCK_OWNWERS',
            new_name='TRUCK_OWNWER',
        ),
    ]
