# Generated by Django 3.2.6 on 2021-09-01 22:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Products', '0004_alter_delivery_note_date_delivered'),
    ]

    operations = [
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tonnages', models.PositiveIntegerField()),
                ('applicable_rate', models.FloatField(blank=True)),
                ('created', models.DateField(blank=True)),
                ('Product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Products.delivery_note')),
            ],
        ),
    ]
