# Generated by Django 3.2.6 on 2021-08-28 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Delivery_Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('material_type', models.CharField(max_length=12)),
                ('delivery_number', models.IntegerField(blank=True)),
                ('plate_number', models.CharField(max_length=12)),
                ('created', models.DateField(auto_now_add=True)),
                ('updated', models.DateField(auto_now=True)),
                ('tonnages', models.FloatField(help_text='tons ')),
                ('material_source', models.CharField(max_length=12)),
                ('material_destination', models.CharField(max_length=12)),
            ],
        ),
    ]
