# Generated by Django 3.2.6 on 2021-08-28 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='delivery_note',
            name='contract_job',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='delivery_note',
            name='material_source',
            field=models.CharField(max_length=20),
        ),
    ]
