# Generated by Django 3.2.6 on 2021-08-28 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0002_auto_20210828_1117'),
    ]

    operations = [
        migrations.AddField(
            model_name='delivery_note',
            name='Date_delivered',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
