# Generated by Django 3.2.6 on 2021-08-28 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0003_delivery_note_date_delivered'),
    ]

    operations = [
        migrations.AlterField(
            model_name='delivery_note',
            name='Date_delivered',
            field=models.DateField(blank=True, null=True),
        ),
    ]
